aplicacion:
  nombre: Twitter example
   
server:
  port: 3306
  
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/pruebas?useSSL=false
    username: zemoga_test_db
    password: Zem0ga.101
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
      
logging:
  level:
    org:
      hibernate:
        SQL: debug

